# Generated by Django 5.2.4 on 2025-07-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CppQues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField()),
                ('option_a', models.CharField()),
                ('option_b', models.CharField()),
                ('option_c', models.CharField()),
                ('option_d', models.CharField()),
                ('correct_answer', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='DjangoQues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField()),
                ('option_a', models.CharField()),
                ('option_b', models.CharField()),
                ('option_c', models.CharField()),
                ('option_d', models.CharField()),
                ('correct_answer', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='JavaQues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField()),
                ('option_a', models.CharField()),
                ('option_b', models.CharField()),
                ('option_c', models.CharField()),
                ('option_d', models.CharField()),
                ('correct_answer', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PythonQues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField()),
                ('option_a', models.CharField()),
                ('option_b', models.CharField()),
                ('option_c', models.CharField()),
                ('option_d', models.CharField()),
                ('correct_answer', models.CharField()),
            ],
        ),
    ]
