# Generated by Django 5.2.4 on 2025-07-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('', 'Choose Gender'), ('male', 'male'), ('female', 'female'), ('others', 'others')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='qualification',
            field=models.CharField(choices=[('', 'Choose Qualification'), ('matriculation', 'matriculation'), ('intermediate', 'intermediate'), ('Diplaoma', 'Diplaoma'), ('Gaduation', 'Gaduation'), ('Master Degree', 'Master Degree')]),
        ),
    ]
