# Generated by Django 5.2.4 on 2025-08-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_examdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdata',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
