# Generated by Django 5.2.4 on 2025-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='subject',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
