# Generated by Django 5.2.4 on 2025-08-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_subject', '0002_attemptanswer_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='chk_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
